ame: Deploy HTML-Documentation created by doxygen on branch gh-pages

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    - name: Create javadoc pages
      run: ant -noinput -buildfile build.xml docs
    - name: Deploy JavaDoc
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/doxygen' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        publish_branch: gh-pages
